baseURL = 'https://desonglll.github.io/blog/'
locale = 'en-us'
title = "Tesung Lin's Blog"

hasCJKLanguage = true
summaryLength = 70
showToc = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/adityatelange/hugo-PaperMod'

[params]
showReadingTime = true

[params.editPost]
URL = "https://github.com/desonglll/blog/tree/main/content"
Text = "Suggest Changes" # edit text
appendFilePath = true
